---
title: "Case Study Report"
author: "Colin Pi, Sharan Ganjam Seshachallam"
date: '2019 2 15 '
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "60%")
library(stringr)
library(dplyr)
library(readr)
```

```{r, tidy=TRUE, cache=TRUE, message=FALSE}
kick.2018 <- read_csv("ks-projects-201801.csv")
```

##Launched-Deadline and Success/Failure

```{r, tidy=TRUE, fig.align='center'}
kick.2018 <- kick.2018 %>% filter(state %in% c("failed","successful")) %>% mutate(diff_date = as.numeric(as.Date(deadline)-as.Date(str_extract(launched, "^.{10}"))))
hist(kick.2018$diff_date, main = "Launched-Deadline", xlab = "Days")

kick.2018$state <- factor(kick.2018$state)

failed <- subset(kick.2018, select = diff_date, subset = state == "failed", drop = T)
successful <- subset(kick.2018, select = diff_date, subset = state == "successful", drop = T)

hist(failed, main = "Launched-Deadline, Failed", xlab = "Days")
hist(successful, main = "Launched-Deadline, Successful", xlab = "Days")

t.test(kick.2018$diff_date ~ kick.2018$state)
```

We are 95% confident that in average the days from launched date to deadline of the failed projects is from 2.93 to 3.10 days longer than that of the successful projects. 

###Success Rate before and after 2017

```{r, tidy=TRUE}
kick.2018 <- kick.2018 %>% mutate(before_2017 = ifelse(launched < "2017-01-01", "Yes","No"))

before.2017 <- subset(kick.2018, select = state, subset = before_2017 == "Yes", drop = T)
after.2017 <- subset(kick.2018, select = state, subset = before_2017 == "No", drop = T)

succ.before.2017 <- sum(before.2017 == "successful")
succ.after.2017 <- sum(after.2017 == "successful")

prop.test(c(succ.before.2017,succ.after.2017), c(length(before.2017), length(after.2017)), correct = FALSE)
```

We are 95% confident that in average the proportion of successful projects after 2017 is 2 to 3% higher than before 2017. 
